### ISSUE TITLE
Disallow the use of the SecurityContextConstraint

### ISSUE THREAD

**Issue by JimBugwadia** [JimBugwadia/openshift-policies#2]
Disallow the use of the SecurityContextConstraint (SCC) anyuid which allows a pod to run with the UID as declared in the image instead of a random UID

**Comment by patelrit** [comment]
@sabre1041 Can you verify this policy

**Comment by JimBugwadia** [comment]
@patelrit - is this the policy?

https://github.com/JimBugwadia/openshift-policies/blob/main/disallow-security-context-constraint-anyuid/disallow-security-context-constraint-anyuid.yaml

**Comment by patelrit** [comment]
Yes. I am not sure if I am on the right track with this one so wanted @sabre1041 to verify

**Comment by sabre1041** [comment]
@JimBugwadia @patelrit Will be validating each of the policies tonight and will provide feedback on the content

**Comment by sabre1041** [comment]
@patelrit @JimBugwadia 

The goal of this policy is to restrict binding against the `anyuid` SecurityContextConstraint.

Policies should be created to prevent the following:

1. Creating a `ClusterRole` or `Role` that does not allow the `use` verb against the `anyuid` scc. The role that we would want to prohibit would be configured similar to the following:

```shell
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
```

2. By default as part of an OpenShift installation, a `ClusterRole` called `system:openshift:scc:anyuid` is created. We would want to prohibit the creation of either a `RoleBinding` or `ClusterRoleBinding` that references this `ClusterRole`

**Comment by patelrit** [comment]
Both cases have been addressed
